Homework1
made-ml-in-prod-2021/alekxd pull request #2
Opened 2021-05-09 20:57 UTC by alekxd

- train.py - основной модуль и приложение для обучения на тренировочной выборке: функции предобработки данных, обучения, загрузки и сохранения данных и моделей
- utils.py - служебный модуль: функции чтения параметров из YAML конфиг файла, инициализации логгинга
- predict.py - приложение для предсказания на тестовой выборке

для EDA применяется pandas-profling

2021-05-13 06:57 UTC, ropalev reviewed
Ветка - 1 балл
Описание к пулу реквесту -2 балла
EDA - 2 балл, PandasProfile наше все, формально выполнено хотя наверно ожидалось что будет делаться самостоятельно
Скрипт для генерации отчета - 1 балл
модульная структура - 2 балла
использованы логгеры - 2 балла
разные конфиги в json или yaml - 1 балл, просто изменяется набор фичей, по факту конфигурация одна
датаклассы для сущностей из конфига - 3
readme для обучения - 2 балла,, понятно что все делают один продет, но в новом виртуальном окружении, могут отсутствовать нужные библиотеки, наверно стоит добавить request.txt,
readme для predict - 2 балла
самооценка - 1 балл

Оценка 19 баллов

Прошу прощения за позднюю проверку

2021-05-24 20:42 UTC, Sergey-Pravdyukov commented on ml_project/src/predict.py
> +from train import load_model, save_prediction, load_data, save_data, convert_df_to_numpy
`train` и `predict` должны быть связаны только посредством артефакта - пикла весов. Вынеси пожалуйста весь общий функционал для `train` и `predict` в отдельный модуль.

2021-05-24 20:44 UTC, Sergey-Pravdyukov commented
Логгеры не нашел.

2021-05-24 20:47 UTC, Sergey-Pravdyukov commented
Нашел конфиги для фич и путей. Для моделей конфигов не нашел.

2021-05-24 20:50 UTC, Sergey-Pravdyukov commented
Датаклассы и конфиги не связаны логически между собой.

2021-05-24 20:54 UTC, Sergey-Pravdyukov commented
Непонятно какие пакеты ставить в окружение. Опиши пожалуйста в `README.md` запуск виртуального окружения, а также добавь пожалуйста `requirements.txt`.

2021-05-24 20:56 UTC, Sergey-Pravdyukov requested changes
Готов усовершенствовать свое решение?

2021-05-24 21:32 UTC, alekxd commented
да, готов )
то что закоммитил сейчас - исправление  замечаний от коллеги студента
когда исправлю все замечания - запрошу re-review

2021-05-25 19:24 UTC, alekxd commented
1. Общие для train и predict функции вынесены в отдельный модуль models.py
2. В readme добавлены команды для создания виртуального окружения и установки зависимостей
3. Приведены в порядок описание параметров в датаклассах и конфиг файлах
4. В конфиг файлы добавлена возможность выбрать тип и параметры модели

2021-05-26 14:14 UTC, Sergey-Pravdyukov approved these changes
Снимаю 1 балл за негибкие монолитные конфиги.

Итого 20 баллов.

2021-05-27 14:51 UTC, merged